name: Cleanup Workflow Runs

on:
  schedule:
    - cron: '0 0 * * 0'  # Run weekly at midnight on Sunday
  workflow_dispatch:  # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    
    steps:
      - name: Delete workflow runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          # Get date from 7 days ago in ISO 8601 format
          CUTOFF_DATE=$(date -d "7 days ago" -u +"%Y-%m-%dT%H:%M:%SZ")
          
          # Get all workflow runs
          echo "Fetching workflow runs..."
          WORKFLOW_RUNS=$(curl -s \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/runs?per_page=100")
          
          # Extract and process run IDs
          echo "Processing workflow runs..."
          echo "$WORKFLOW_RUNS" | jq -r --arg DATE "$CUTOFF_DATE" \
            '.workflow_runs[] | select(.created_at < $DATE) | .id' | \
          while read -r RUN_ID; do
            echo "Deleting workflow run $RUN_ID..."
            curl -s \
              -X DELETE \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID"
          done
          
          echo "Cleanup complete!"

      - name: Delete old artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          # Get artifacts
          echo "Fetching artifacts..."
          ARTIFACTS=$(curl -s \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/artifacts?per_page=100")
          
          # Delete artifacts older than 7 days
          echo "Processing artifacts..."
          echo "$ARTIFACTS" | jq -r '.artifacts[] | select(.created_at < "'$(date -d "7 days ago" -u +"%Y-%m-%dT%H:%M:%SZ")'") | .id' | \
          while read -r ARTIFACT_ID; do
            echo "Deleting artifact $ARTIFACT_ID..."
            curl -s \
              -X DELETE \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$REPO/actions/artifacts/$ARTIFACT_ID"
          done
          
          echo "Artifact cleanup complete!"