name: Docker Build and Push

on:
  push:
    branches:
      - my-customizations
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Initial disk space check
        run: |
          echo "=== Initial Disk Space Status ==="
          df -h
          docker system df

      - name: System cleanup
        run: |
          echo "=== Starting System Cleanup ==="
          
          # Remove unused Docker resources
          docker system prune -af --volumes
          
          # Remove package manager cache
          sudo apt-get clean
          sudo apt-get autoremove -y
          sudo rm -rf /var/lib/apt/lists/*
          
          # Remove development tools and languages not needed
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /opt/hostedtoolcache/*
          
          # Clear temp directories
          sudo rm -rf /tmp/*
          sudo rm -rf /var/tmp/*
          
          echo "=== Post-Cleanup Disk Space ==="
          df -h

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set repository and image name to lowercase
        run: |
          echo "IMAGE_NAME=${IMAGE_NAME,,}" >> ${GITHUB_ENV}
          echo "FULL_IMAGE_NAME=${REGISTRY}/${IMAGE_NAME,,}" >> ${GITHUB_ENV}
        env:
          IMAGE_NAME: '${{ github.repository }}'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.FULL_IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=git-
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Pre-build space check
        run: |
          echo "=== Available Space Before Build ==="
          df -h
          available_space=$(df / | awk 'NR==2 {print $4}')
          if [ $available_space -lt 5000000 ]; then  # Less than 5GB
            echo "::warning::Low disk space before build: Less than 5GB available"
            exit 1
          fi

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.local
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ github.workflow }}
          cache-to: type=gha,mode=max,scope=${{ github.workflow }}
          build-args: |
            BUILD_HASH=${{ github.sha }}
            USE_CUDA=true
            USE_CUDA_VER=cu121
            CACHEBUST=${{ github.sha }}
          outputs: type=docker,compression-level=9,force-compression=true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Final disk space check
        if: always()
        run: |
          echo "=== Final Disk Space Status ==="
          df -h
          docker system df

      - name: Debug - Display Docker build output
        if: failure()
        run: |
          mkdir -p logs
          docker buildx build --progress=plain -f Dockerfile.local . 2>&1 | tee logs/build_output.log
          echo "Last 1000 lines of build output:"
          tail -n 1000 logs/build_output.log

      - name: Upload build log as artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: docker-build-log
          path: logs/build_output.log
          retention-days: 3